#!/usr/bin/env python3
"""
eda.py — exploratory analysis on the cleaned dataset.

Input : data/processed/clean_cases.csv
Output: reports/figures/*.png
        reports/eda_findings.md   (every number quoted comes from this run)

Replaces the original eda.ipynb (106 cells, much of it repeated/abandoned
work) with one linear pass over the corrected data.
"""
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "processed" / "clean_cases.csv"
FIG_DIR = ROOT / "reports" / "figures"
REPORT = ROOT / "reports" / "eda_findings.md"

# validated categorical palette (see dataviz skill, references/palette.md)
BLUE, ORANGE, AQUA, YELLOW, MAGENTA, GREEN, VIOLET, RED = (
    "#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948",
)
INK = "#0b0b0b"
MUTED = "#898781"
GRID = "#e1e0d9"

plt.rcParams.update({
    "figure.facecolor": "#fcfcfb",
    "axes.facecolor": "#fcfcfb",
    "axes.edgecolor": GRID,
    "axes.labelcolor": INK,
    "text.color": INK,
    "xtick.color": MUTED,
    "ytick.color": MUTED,
    "axes.grid": True,
    "grid.color": GRID,
    "grid.linewidth": 0.8,
    "font.size": 11,
    "axes.spines.top": False,
    "axes.spines.right": False,
})


def savefig(name):
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(FIG_DIR / name, dpi=150)
    plt.close()


def main():
    df = pd.read_csv(DATA, parse_dates=["date", "hearing_date"])
    n = len(df)
    lines = []
    lines.append("# EDA Findings\n")
    lines.append(f"Generated by `src/eda.py` against the {n}-case cleaned dataset "
                  f"(`data/processed/clean_cases.csv`). Every figure and number below "
                  f"comes directly from that file.\n")

    # 1. Outcome distribution (labeled cases only)
    labeled = df[df["outcome"].notna()]
    outcome_counts = labeled["outcome"].value_counts()
    plt.figure(figsize=(7, 4.2))
    plt.barh(outcome_counts.index[::-1], outcome_counts.values[::-1], color=BLUE)
    plt.title(f"Judgment outcomes (labeled n={len(labeled)} / {n})")
    plt.xlabel("Number of cases")
    savefig("01_outcome_distribution.png")
    lines.append("## Outcome distribution\n")
    lines.append(f"Only {len(labeled)} of {n} cases ({len(labeled)/n:.1%}) have an outcome "
                 f"the extraction pipeline could actually find in the judgment text; the "
                 f"rest are genuinely missing and are excluded here (not counted as a fake "
                 f"'unknown' outcome). Among the labeled cases:\n")
    for k, v in outcome_counts.items():
        lines.append(f"- **{k}**: {v} ({v/len(labeled):.1%} of labeled cases)")
    lines.append(f"\n'Set aside' dominates ({outcome_counts.get('set aside',0)} cases) — "
                 f"consistent with a Supreme Court appellate docket, where a large share of "
                 f"the matters that reach a full hearing result in the lower court's order "
                 f"being set aside and remanded, rather than a flat dismissal.\n")

    # 2. Cases per year
    yearly = df.dropna(subset=["year"]).groupby("year").size()
    plt.figure(figsize=(8, 4))
    plt.bar(yearly.index.astype(int).astype(str), yearly.values, color=BLUE)
    plt.title("Cases per year")
    plt.xticks(rotation=90)
    plt.ylabel("Number of cases")
    savefig("02_cases_per_year.png")
    lines.append("## Cases per year\n")
    top_year = yearly.idxmax()
    lines.append(f"Case counts run from {int(yearly.index.min())} to {int(yearly.index.max())}, "
                 f"peaking in {int(top_year)} with {int(yearly.max())} cases. Coverage is uneven "
                 f"in earlier years — this is a corpus-composition artifact of what was "
                 f"available to collect, not a claim about actual Supreme Court caseload "
                 f"over time.\n")

    # 3. Case type / legal category
    ct = df["case_type"].value_counts()
    plt.figure(figsize=(7.5, 4.2))
    colors = [BLUE, ORANGE, AQUA, YELLOW, MAGENTA, GREEN, VIOLET][: len(ct)]
    plt.barh(ct.index[::-1], ct.values[::-1], color=list(reversed(colors)))
    plt.title("Case type")
    plt.xlabel("Number of cases")
    savefig("03_case_type.png")
    lines.append("## Case type\n")
    lines.append(f"{ct.get('Unclassified',0)} of {n} cases ({ct.get('Unclassified',0)/n:.1%}) "
                 f"could not be classified — there was no `case_no` text for the classifier "
                 f"to read, not a guess forced into a bucket. Among the rest, "
                 f"{ct.drop('Unclassified', errors='ignore').idxmax()} is the largest group "
                 f"({ct.drop('Unclassified', errors='ignore').max()} cases).\n")

    # 4. Word count distribution
    wc = df["word_count"].dropna()
    plt.figure(figsize=(7.5, 4.2))
    plt.hist(wc, bins=40, color=BLUE)
    plt.title("Judgment length (word count)")
    plt.xlabel("Word count")
    plt.ylabel("Number of cases")
    savefig("04_word_count_distribution.png")
    lines.append("## Judgment length\n")
    lines.append(f"Word count: mean {wc.mean():.0f}, median {wc.median():.0f}, "
                 f"max {wc.max():.0f}. The distribution is right-skewed — most judgments "
                 f"are a few thousand words, with a long tail of much longer, more complex "
                 f"rulings.\n")

    # 5. Word count by outcome (only where outcome is labeled)
    order = labeled.groupby("outcome")["word_count"].median().sort_values().index
    plt.figure(figsize=(7.5, 4.2))
    data_by_outcome = [labeled[labeled["outcome"] == o]["word_count"].dropna() for o in order]
    bp = plt.boxplot(data_by_outcome, labels=order, patch_artist=True, showfliers=False)
    for patch in bp["boxes"]:
        patch.set_facecolor(BLUE)
        patch.set_alpha(0.55)
    plt.xticks(rotation=30, ha="right")
    plt.title("Judgment length by outcome (labeled cases only)")
    plt.ylabel("Word count")
    savefig("05_word_count_by_outcome.png")

    # 6. Top cited sections
    from collections import Counter
    import ast
    all_sections = Counter()
    for s in df["sections_list"].dropna():
        try:
            vals = ast.literal_eval(s) if isinstance(s, str) else s
        except (ValueError, SyntaxError):
            vals = []
        all_sections.update(vals)
    top_sections = all_sections.most_common(12)
    labels_s = [str(k) for k, _ in top_sections]
    values_s = [v for _, v in top_sections]
    plt.figure(figsize=(7.5, 4.5))
    plt.barh(labels_s[::-1], values_s[::-1], color=BLUE)
    plt.title("Most frequently cited section numbers")
    plt.xlabel("Number of cases citing this section")
    plt.ylabel("Section number")
    savefig("06_top_sections.png")
    lines.append("## Most-cited sections\n")
    lines.append("Section numbers are extracted without their governing statute, so "
                 "`302` could mean PPC s.302 (murder) in one case and a different act's "
                 "s.302 in another — this chart describes *which numbers recur*, not "
                 "confirmed legal categories. The most frequent: " +
                 ", ".join(f"{k} ({v} cases)" for k, v in top_sections[:5]) + ".\n")

    # 7. Bench size (only the reliably-known subset)
    bs = df["bench_size"].dropna()
    lines.append("## Bench size\n")
    lines.append(f"A reliable bench size is only available for {len(bs)} of {n} cases "
                 f"(see the data quality report for why). Among those: "
                 f"median {bs.median():.0f}, largest {bs.max():.0f}.\n")

    # 8. Legal category
    lc = df["legal_category"].value_counts()
    plt.figure(figsize=(6.5, 4))
    colors2 = [BLUE, ORANGE, AQUA, YELLOW][: len(lc)]
    plt.barh(lc.index[::-1], lc.values[::-1], color=list(reversed(colors2)))
    plt.title("Legal category (heuristic)")
    plt.xlabel("Number of cases")
    savefig("07_legal_category.png")

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines))
    print(f"Wrote {len(list(FIG_DIR.glob('*.png')))} figures to {FIG_DIR}")
    print(f"Wrote {REPORT}")


if __name__ == "__main__":
    main()
